### ISSUE TITLE
Senaryo Parametreleri

### ISSUE THREAD

**Issue by canibal1** [teknofest-suruiha/suruiha#10]
senaryo parametrelerinde run_uav.launch dosyası diye bir dosya ismi geçiyor ama dökümanlarda buna rastlamadım. Daha sonra mı eklenecek acaba?

**Comment by okanasik** [comment]
Evet, bahsedilen örnek takım kodları eklenip net bir şekilde dokümante edilince herkese tekrar duyuracağız.
