### ISSUE TITLE
Hava Trafik Kontrolcüsü Hakkında

### ISSUE THREAD

**Issue by ghost** [teknofest-suruiha/suruiha#11]
Merhaba. Senaryoyu çalıştırıp aşağıdaki şekilde servise erişmeye çalışıyorum.
`result = air_traffic_service("zephyr0", STATUS)`
Çıktı olarak "AVAILABLE" alıyorum.
Sonrasında kalkış izni istiyorum.
`result = air_traffic_service("zephyr0", TAKEOFF_REQUEST)`
Çıktı olarak "ALLOCATED_TO_TAKEOFF" alıyorum.
Tekrar istek yaptığımda "TAKEN" cevabını alıyorum.
Buraya kadar bir problem yok. Fakat,
`result = air_traffic_service("zephyr0", STATUS)` yapsam da
`result = air_traffic_service("zephyr1", STATUS)` yapsam da sonuç olarak "READY_TO_TAKEOFF" cevabını alıyorum. 
Oysa ki 
`result = air_traffic_service("zephyr1", STATUS)` yaptığımda "TAKEN" cevabını almalıyım değil mi?
Wiki sayfasında böyle yazmakta.
Problem benden mi yoksa kontrolcüden mi kaynaklanıyor?
Selamlar...

**Comment by okanasik** [comment]
Merhabalar, problem hava trafik kontrolcüden kaynaklanıyor. İniş ve kalkış yapan uçağın isminin kontrol edilmediği görülüyor. Bu hatayı giderince tekrar duyuracağız.

**Comment by ghost** [comment]
@okanasik İlginiz için çok teşekkürler.
Ayrıca karşılaştığım bir problem de İHA'ların kalan bataryalarını ve batarya kapasitelerini okumak istediğimde, Hava Trafik Kontrolcüsü'nden kalkış için izin almadan okuduğumda bu değerlerin 0 olduğunu görüyorum. Bu bir problem mi yoksa kısıtlamalardan biri mi? İHA'ların kalkış isteği ve kalkış yapmadan önce batarya kapasitelerine göre dolaşacakları maksimum alanı hesaplayarak İHA'lara batarya kapasitelerine göre sorumluluklar yükleyen bir algoritma geliştirdim. Bu başlangıç ayarlamalarını İHA'lar kalkış yapmadan önce yapmak istiyorum. Bu ayarlamaları kalkıştan sonra mı yapmalıyım yoksa yoksa bunu da bir hata olarak görüp gidermenizi mi beklemeliyim?
Selamlar, iyi çalışmalar...

edit: senaryo parametrelerinden batarya kapasitelerinin çekilebildiğini gördüm. yine de bir problemin olup olmadığının kontrol edilmesi adına mesajı tutuyorum.
edit2: Hava Trafik Kontrolcüsü'nden kalkış için izin aldıktan sonra okumaya çalışsam dahi simülasyon hızına bağlı ilk birkaç değerleri 0 görebilmekteyim (bazen ilk değerleri hemen okuyabiliyor bazen ise ilk 5-6 değer 0 gelebiliyor).
edit3: sorunu okuduğum değerleri 0'dan başka bir değer görene kadar döngü içinde sürekli okuyarak ana akışı duraklatıp geçici olarak çözdüm.

**Comment by okanasik** [comment]
@mustaphos Biraz önce hava trafik kontrolcüsüyle ilgili değişiklikleri depoya gönderdim. Tekrar test edebilir misiniz? Bu son haliyle trafik kontrolcü kendisine mesaj gönderen İHA'ya göre pistin durumunu dönüyor.

Pil yöneticisi kodu herhangi bir mesaj almamışsa kalan ve mevcut pil kapasitesi 0 değeri göreceksiniz. Ama aslında olan henüz mesaj almamış olmanızdır. Hava trafik kontrolcüsünden `READY_TO_TAKEOFF` mesajı alana kadar pil ile ilgili herhangi bir mesaj alamıyor olacaksınız. Ama İHA'ları seçerken kapasitelerini değerlendirmek isterseniz bunu senaryo parametrelerinden yapabilirsiniz. Senaryoda sunulan tüm İHA'ların pil kapasiteleri belirtilmektedir.

**Comment by ghost** [comment]
@okanasik Teşekkürler. 
Güncelleyip çalıştırdım.
Şu an bir problem görmediğim için konuyu kapatıyorum.
Kolay gelsin.
