### ISSUE TITLE
paket adı ve dizin hazırlanması

### ISSUE THREAD

**Issue by canibal1** [teknofest-suruiha/suruiha#12]
takım ismi Sürü Hazerfan olsun paket adı ve dizin adı suru_hazerfan olmalıdır. yazıyor wiki de. Sample_Team olan herşeyi değiştirdim ama yinede şu hatayı veriyor. [uykusuz_muhendisler_1-1] process has died [pid 2421, exit code 1, cmd /home/canibal/catkin_ws/src/suruiha_uykusuz_muhendisler/uykusuz_muhendisler/scripts/uav_controller.py 1 __name:=uykusuz_muhendisler_1 __log:=/home/canibal/.ros/log/b00b5ea0-a731-11e8-aa85-ca4595dd7750/uykusuz_muhendisler_1-1.log].
log file: /home/canibal/.ros/log/b00b5ea0-a731-11e8-aa85-ca4595dd7750/uykusuz_muhendisler_1-1*.log
 yardımcı olabilir misiniz?

**Comment by canibal1** [comment]
çözdüm

**Comment by Shubuo** [comment]
R

Gönderildiği araç: Android için BlackBerry Hub<http://play.google.com/store/apps/details?id=com.blackberry.hub>
Gönderen: notifications@github.com
Gönderilen: 25 Ağustos 2018 02:30
Alıcı: suruiha@noreply.github.com
Yanıtlama adresi: reply@reply.github.com
Cc: subscribed@noreply.github.com
Konu: Re: [teknofest-suruiha/suruiha] paket adı ve dizin hazırlanması (#12)



Closed #12<https://github.com/teknofest-suruiha/suruiha/issues/12>.
