### ISSUE TITLE
Batarya Seviyeleri Hakkında

### ISSUE THREAD

**Issue by ghost** [teknofest-suruiha/suruiha#13]
Merhaba.
Senaryo süresini, canlı yayında gösterdiğiniz biçimde uzatıp geliştirme çalışmaları için yeterli vakit oluşturabiliyorum fakat bu sefer İHA'ların pili bu süreyi kısıtlıyor. 
İniş kalkış ile pili tekrar yenileyebileceğimi biliyorum fakat bunu öncesinde test etmem gereken birtakım algoritmalar var.
`src/suruiha/scenarios/scenarios/test0.yaml` içerisindeki pil kapasitelerini değiştirmeme rağmen simülasyonda pil seviyeleri hala sabit ve 1000 olarak kalıyor.
Bu sorunu nasıl çözebilirim?
Teşekkürler...

**Comment by ghost** [comment]
@okanasik

**Comment by okanasik** [comment]
Merhabalar, scenario dosyasının yanında İHA'nın kendi model dosyasını da değiştirmeniz gerekiyor. `catkin_ws/src/suruiha/uav_description/gazebo_models/iris_quadrotor_with_plugin/model.sdf` ve  `catkin_ws/src/suruiha/uav_description/gazebo_models/zephyr_fixed_wing/zephyr_fixed_wing.sdf` dosylarındaki battery capaticy ile ilgili olan yerleri de düzenlemeniz gerekiyor. Kolaylıklar.

**Comment by ghost** [comment]
çalışıyor
