### ISSUE TITLE
Tespit ve Takip İşlemleri Hakkında 

### ISSUE THREAD

**Issue by ghost** [teknofest-suruiha/suruiha#14]
@okanasik Okan bey merhabalar.
Tespit ve takip işlemlerinde öncelikle terörist tespit işlemleri üzerine çalışıyorum.
Yazdığım kodda sensörün gördüğü herşeyi ekranı basacağı birkaç satırlık işlemler yazdım.
Teröristlerin gideceği binaya ((-300, 300) koordinatlarındaki) gitmesi için yeterli süre verdim.
Daha sonra otonom olarak İHA ile bu bina üzerine geldiğimde teröristleri sensör verilerinden alabiliyorum fakat binanın adı ve konum verisi sensöre gelmiyor.
Bu durum diğer binaların üzerine geldiğimde de geçerli.
İHA'lar ile yeşil alana (simülasyondaki çimenlik düzlem) girip çıktığımda ise ground plane, building 0,1,2,3 şeklinde bir veriyi bir anda alıyorum.
Fakat binalar üzerinde uçtuğumda bu veriler teker teker gelmiyor (örneğin building_1'in üzerinde uçtuğumda sadece bunun adı ve konumu gelmeli fakat bir veri alamıyorum).
Ayrıca aldığım terörist verileri de uçurduğum İHA (-300,300) konumunda uçarken değil belirli bir süre sonra geliyor. 
Gözle görülür bir gecikme var.
Bu problemleri nasıl çözebilirim?
İyi çalışmalar...

**Comment by ghost** [comment]
Ayrıca arama yapılacak alanı ikiye böldüm ve iki İHA'ya tahsis ettim.
Sadece teröristleri gördüğüm anda isim ve poz bilgilerini ve çıktıkları binanın (building_1) bilgilerini hakem sunucusuna gönderdim (örnek takım kodlarındaki tespit takim işlemlerini aynı şekilde bıraktım).
Herhangi bir takip işlemi yapmamama rağmen takip puanım sürekli arttı ve simülasyon sonunda takip puanım 85 seviyesine kadar yükseliyor.
Not olarak İHA'ların pil seviyesini 3000'e ve simülasyon süresini 50dk'ye çıkarttığımı belirtmek isterim.

**Comment by okanasik** [comment]
Merhabalar,
Biraz önce yaptığım değişiklikleri alıp tekrar deneyebilir misiniz?
Kabaca şu değişiklikleri yaptım:
- uav_sensor modülü en az bir nesne gördüğünde mesaj yayınlayacak.
- uav_sensor modülü binaları çerveleyen kutunun kamera görüntüsüne girdiği anda algılayacak. Daha önceden binanın orta noktasının kamera görüntüsüne girmesi gerekiyordu.
- uav_sensor modülü binaların (building_) pozisyonlarını doğru şekilde geri dönüyor. Daha önce görülen binaların pozisyonları 0, 0, 0, 0, 0, 0 şeklinde dönülüyordu.
- Gazebo modelinde bottom_camera özellikleri sanal kamera ile eşitlendi. Topic visualization kısmında zephyr uçağının aşağı bakan kamerasını görüntülerseniz sanal kameranın gördüğü alanı siz de gözle görebilirsiniz.

**Comment by okanasik** [comment]
Takip işlemi yapmasanız bile gördüğünüz terörist pozisyonlarını paylaşmanız takip etme puanınızı arttıracaktır. Bilinçli bir takip işlemi yapmadan 85 puana ulaşmanız biraz ilginç olmuş. Simülasyon süresi uzatıldığında teröristler diğer binaya varınca artık o noktada bekliyorlar. Bu aşamada sizin son pozisyon bildirimleriniz teröristlerin son bulunduğu noktaya yaklaştıkça takip puanınız artmış olmalı. Normalde teröristlerin takiplerinin ne zaman başlatılacağına dair bir zaman tutuyoruz. Bir de takibin ne zaman bitirileceğine dair bir süre kullanmamız bu problemi çözecektir. Çözünce tekrar buradan bildireceğim.

**Comment by ghost** [comment]
@okanasik bey "uav_sensor modülü sadece bir nesne gördüğünde mesaj yayınlayacak." 
Böyle bir kısıtlamaya neden gidildi?
Örneğin İHA terörist grubunun üzerinde uçmakta. 
Kadraja birden fazla terörist girdiğin farz edelim. 
Böyle olduğunda (hemen hemen) rastgele bir terörist seçilecektir. 
Bir teröristin üzerinde uçsak dahi şansa bağlı olarak bunu görmeyip bildiremeyebiliriz veya geç bildirilebilir.
Örnek veriyorum kadrajda 1-10'a kadar terörist var fakat hep 5. olan denk geldi sensöre.
Teröristler grup halinde hareket etmeyecekse veya bir kısmı farklı noktalara gidecekse bu durumda tespit takip işlemleri biraz zorlaşacak.
Yani kısacası grubun üzerinde uçtuğumuz zaman teröristleri tespit etmemiz zorlaşmayacak mı?
Ayrıca takip işlemi olarak sadece teröristleri sanal kamera sensöründe gördüğümde görülme mesajı gönderdim.
Bu görülme mesajını atmadığım zamanlarda dahi takip puanı yavaşça artmakta.
Problemi tam olarak ne yaptığımda gördüğümü tespit edebilirsem sizinle paylaşırım. 
Selamlar.

**Comment by okanasik** [comment]
Merhabalar,
 "uav_sensor modülü sadece bir nesne gördüğünde mesaj yayınlayacak." kusura bakmayın yanlış yazmışım. En az bir nesne görüldüğünde mesaj gönderilecek. Mevcut durumda hiç bir nesne görülmese de boş bir mesaj gönderiyordu modül :)

**Comment by ghost** [comment]
İlginiz için çok teşekkür ediyorum hocam.
Kolay gelsin.
Deneyip sorun düzeldiğinde konuyu kapatacağım.
İyi günler...

**Comment by okanasik** [comment]
Merhabalar,
Takip puanlama sistemi ile ilgili değişiklikleri şimdi gönderdim. Takipten puan almak için teröristlerin takip ettiği anlarda takip mesajlarının gönderilmesi gerekiyor. Teröristlerin hareketleri sonlanınca takip puanında herhangi bir değişiklik olmuyor.

**Comment by ghost** [comment]
Selamlar @okanasik hocam.
Sensör modülü şu an doğru çalışmakta.
İHA evlerin üzerine geldiğinde doğru bir şekilde verileri alabiliyorum.
Takip puan sisteminin de doğruluğunu kontrol ettiğimde konuyu kapatacağım.
Kolaylıklar...

**Comment by ghost** [comment]
@okanasik hocam şöyle bir durumla karşılaştım.
Bir İHA'yı sırasıyla pistten kaldırıp önce building_1'e sonra building_3'e gönderdim.
İHA, aşağıdaki konumda iken building_1'i (300, 300) tespit etti.
`First building detected when UAV at x: 297.687779442 y: 281.273302965 z: 91.0188756369`
İHA, aşağıdaki konumda iken building_3'ü  (300, -300) tespit etti.
`Second building detected when UAV at x: 297.507295814 y: 14.6341391214 z: 89.8535499924`
Bu sonuçların İHA'nın konumuna göre tespit yerleri bana doğru gelmedi çünkü aynı uçuş düzeninde ve aynı irtifada ilk bina 25metre uzakta iken, diğer bina ise 310metre uzaktayken tespit edilebiliyor.
Bunun sebebi nedir?
Bina tespiti tam olarak nasıl yapılmakta?
Kolay gelsin.

**Comment by ghost** [comment]
Yukarıdaki problem iki saat önceki kodlarınızda gözüküyordu.
Bir saat önceki yaptığınız katkıdaki koda göre yaptığım simülasyonda da bu devam etmekte.
`First building detected when UAV at x: 315.87835477 y: 254.526064942 z: 90.989915296`
`Second building detected when UAV at x: 298.158059365 y: 20.1675494593 z: 86.6350553357`

**Comment by okanasik** [comment]
Eğer zephyr kullanıyorsanız `/uav_description/gazebo_models/zephyr_with_skid_pad/zephyr_with_skid_pad.sdf` dosyasında `bottom_cam_logical` tag'inin visualize değerini `true` yapıp İHA hareket ederken o binanın görüntü alanına girip girmediğinden emin olabilir misiniz? Eğer İHA'nın rotasyonu bir şekilde çok büyükse böyle bir durum olabilir. Eğer iris kullanıyorsanız şu dosyada benzer değişikliği yapıp test edebilir misiniz? `uav_description/gazebo_models/iris_quadrotor/model.sdf`

**Comment by ghost** [comment]
Merhabalar.
Hocam görüntü alanı İHA'nın roll ve pitch değerlerine bağlı olarak hareket etmekte.
Roll ve pitch'ten bağımsız (yaw açısına bağımlı olabilir) olması uygulamada camera gimbal işlemleri ile yapılabiliyor gerçek hayatta.
Kameranın İHA'nın sağa/sola yatış ve yükseliş/dalış hareketlerinden bağımsız olması bence önemli çünkü bu hareketleri yaparken rotasının ve görüş mesafesinin çok uzağındaki nesneleri tespit edebilir.  
Öncelikle bundan şüphe etmiştim.
İHA'nın burnu yerden yükseldiğinde kamera görüş alanı ileriye bakacak ve çok ilerideki objeleri de görebilecektir.
Fakat ikinci binayı hemen hemen aynı koordinatlarda tespit ettiğinde İHA gayet stabil bir şekilde (yere paralel, İHA görüş alanı zemine dik) şaşırtıcı bir şekilde diğer bina da tespit ediliyor.
Kameranın stabil olması gerekli fakat sanırım problem bundan kaynaklanmıyor.
Edit: Kamera görüş alanı sonsuza kadar gidiyor. 
Bir şekilde sanırım sonsuzda binaları kapladığı alanların koordinatları ile görüş alanı kesişiyor bu da sensörün binaları tespit edebilmesine olanak sağlıyor.
Aşağıya üç adet ekran görüntüsü ekledim.
Görüntülerin birinde tespit edilen bina yok.
İkincisinde building_1, üçüncüsünde building_3 tespit edildiği anda ekran görüntüsü aldım.
Kolay gelsin. 
![screenshot 2018-09-10 13 37 37](https://user-images.githubusercontent.com/15967032/45293025-ac966e00-b4ff-11e8-9afe-b7b180d056a3.png)
![screenshot 2018-09-10 13 40 20](https://user-images.githubusercontent.com/15967032/45293026-ac966e00-b4ff-11e8-98dc-c254714006db.png)
![screenshot 2018-09-10 13 43 13](https://user-images.githubusercontent.com/15967032/45293027-ac966e00-b4ff-11e8-92f4-04a2d19ee16f.png)

**Comment by ghost** [comment]
İlk binayı tespit ederken de sanırım eğer binanın tamamı görüş alanı içinde ise tespit ediliyor.
İlk fotoğrafta gördüğünüz üzere binanın yarısı görülse dahi tespit edilmemekte.
Tamamı görüldükten sonra tespit edilebiliyor.
Terörist grafiği topladığı alan bakımından küçük olduğundan görüldüğü anda tüm cad grafiği görülebilir fakat evler gibi büyük grafiklerin tamamının kadraja girmesinin olasılığı çok düşük.
90 metre gibi kamera sensörünün maksimum çalışma irtifasına (100m) yakın bir yükseklikte uçmama rağmen ev grafiği kamera görüntüsüne ancak girebilmekte.
![screenshot 2018-09-10 13 55 46](https://user-images.githubusercontent.com/15967032/45293805-e1a3c000-b501-11e8-9a1e-358945d1b366.png)
![screenshot 2018-09-10 13 55 53](https://user-images.githubusercontent.com/15967032/45293811-e799a100-b501-11e8-85d4-fd8280967c90.png)
![screenshot 2018-09-10 13 58 55](https://user-images.githubusercontent.com/15967032/45293813-eb2d2800-b501-11e8-815a-5633c4816582.png)

**Comment by okanasik** [comment]
Kendi testlerimde bu durumla karşılaşmadım ama görüş alanı çizimini maksimum yüksekliğe güncelledim ve görülebilir nesnelerin görülebilmesi için uzaklık kontrolü ekledim. bir de bu şekilde deneyebilir misiniz? Ayrıca nesnelerin görülebilmesi için tamamının görüntü alanı içinde olmasına gerek yok. Nesneleri çevreleyen box'ın her hangi bir kısmı görüş alanına giriyorsa o nesne görülmüş oluyor. Tekrar test edip geri bildirimde bulunursanız çok iyi olur. Bunun doğru çalışması çok önemli.

**Comment by ghost** [comment]
@okanasik hocam emeğiniz için teşekkürler.
Şu an bir problem görmemekteyim.
Binaların tespiti doğru bir şekilde çalışıyor.
Yine bir problem görürsem size bildiririm.
Selamlar...

**Comment by ghost** [comment]
Son gönderdiğiniz commit ile sensör ve verileri problemsiz ve stabil olarak çalışmakta konuyu kapatıyorum.
Teşekkürler...
