### ISSUE TITLE
İniş İşlemleri Hakkında

### ISSUE THREAD

**Issue by ghost** [teknofest-suruiha/suruiha#15]
Merhaba.
İniş ve yeniden batarya doldurma konusunda dökümantasyon ve kodlar hakkında sanırım birtakım eksiklikler var.
Birincisi örnek senaryodaki inişin bittiği nokta yanlış.
İkincisi iniş pisti normal bir piste göre çok küçük ve iniş başlangıç pozisyonu 50m olarak belirlenmiş.
Bu şekilde sabit kanatlı İHA'nın piste iniş yapabilmek için çok agresif manevralar yapmak gerekiyor bu da uçuşun stabil olmayan bir hale gelmesine yol açıyor.
Motor dönüş hızı sıfırlansa dahi pisti kaçırma ihtimali çok yüksek.
Bu sebeple iniş prosedürlerinden iniş pozu prosedürünü çıkarmayı veya iniş başlangıç yüksekliğinin düşürülmesini (5-10m düzeylerinde olmasını) öneriyorum.
Kalkış yapmış bir İHA'nın pilini bir süre harcadıktan sonra geri gelip pilini yenilemesi amaçlı iniş yaptığının kontrol edilmesi için İHA'nın iniş pisti üzerinde olması, hızının 0 veya çok az olması (eğer aşağıda belirttiğim İHA - iniş pisti arasındaki sürtünme simülasyon ortamına eklenirse 0 'a yakın hız kabul edilebilir, onun dışında İHA yerdeki hareketine 3-5m/s olarak devam edebiliyor motor hızı 0 belirlense dahi) ve irtifasının 0 veya çok az olması kontrolleri bence yeterlidir.
Ayrıca iniş pisti ve İHA arasında bir sürtünme kuvveti yok.
Bu da iniş yaparken İHA disarm (tüm kontrol komutları 0) olsa dahi İHA yerde hareketine devam ediyor.
Son olarak da şu anki prosedürlere uygun olarak iniş yaptım fakat trafik kontrolcüsünün pili yenilediği ve uçağın başlangıç konumuna getirdiğini göremedim. 
Bu prosedürde bir eksiklik mi var?
Selamlar...

**Comment by ghost** [comment]
Yaptığım bir denemede öncelikle iniş pozunu istedim ve sonrasında iniş isteği yaptım.
İniş isteği yaptıktan sonra aşağıdaki noktalara sırasıyla gittim.
İnişin başlangıcı
```
X = 495.58 Y = -398.03 Z = 50.87
```
İnişin bitişi 
```
X = 492.59 Y = -483.04 Z = 0.25
```
İHA şu an iniş bitişinde sabit olarak durmakta fakat kontrocüden hala
 `Traffic: ALLOCATED_TO_LAND` cevabını alıyorum.

**Comment by okanasik** [comment]
Sorun çözüldüğü için sorunu kapatıyorum.
