### ISSUE TITLE
Yarışma Deposunun Kurulum Hatası

### ISSUE THREAD

**Issue by eyupucmaz** [teknofest-suruiha/suruiha#18]
**Yarışma paketlerini /home/<usurname>/catkin_ws/src  klasörüne indirdikten sonra yapılan "catkin_make" işleminde hata aldım. Hata kodları aşağıdaki gibi yardımcı olursanız sevinirim.**

ubuntupc@ubuntu-pc:~/catkin_ws$ catkin_make
Base path: /home/ubuntupc/catkin_ws
Source space: /home/ubuntupc/catkin_ws/src
Build space: /home/ubuntupc/catkin_ws/build
Devel space: /home/ubuntupc/catkin_ws/devel
Install space: /home/ubuntupc/catkin_ws/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/ubuntupc/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: 
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/ubuntupc/catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- nosetests not found, Python tests can not be run (try installing package 'python-nose')
-- catkin 0.7.8
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 6 packages in topological order:
-- ~~  - scenarios
-- ~~  - suruiha_gazebo_plugins
-- ~~  - sample_team
-- ~~  - uav_description
-- ~~  - uav_gazebo
-- ~~  - uav_ground_control
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'scenarios'
-- ==> add_subdirectory(suruiha-master/scenarios)
-- Could NOT find roscpp (missing: roscpp_DIR)
-- Could not find the required component 'roscpp'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /usr/share/catkin/cmake/catkinConfig.cmake:82 (find_package):
  Could not find a package configuration file provided by "roscpp" with any
  of the following names:

 roscppConfig.cmake
 roscpp-config.cmake

  Add the installation prefix of "roscpp" to CMAKE_PREFIX_PATH or set
  "roscpp_DIR" to a directory containing one of the above files.  If "roscpp"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  suruiha-master/scenarios/CMakeLists.txt:10 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/ubuntupc/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntupc/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by okanasik** [comment]
Merhabalar,
Kurulum adımlarını eksiksiz tamamladığınızdan emin olun. Sanki ros hiç kurulu değilmiş gibi roscpp'yi bulamıyor. Bu en temel ros kütüphanesidir. Çözüme ulaştıysanız sorunu kapatabilir misiniz?
