### ISSUE TITLE
Surüiha'da yapılan değişiklik sonrası sensör verisi okuyamıyoruz.

### ISSUE THREAD

**Issue by kadirozgun** [teknofest-suruiha/suruiha#19]
Node::Advertise(): Error advertising a topic. Did you forget to start the discovery service?
Senaryo çalıştırdığımız terminalde böyle bir çıktı görmekteyiz. Ve sensörden terörist ya da bina okuma verisi alamıyoruz. Normalde çalışmaktaydı.

**Comment by okanasik** [comment]
Merhabalar,
Daha önce İHA herhangi bir nesne görmese belirli aralıklarda mesaj gönderiyordu. Siz bu davranışa göre çalışan bir şey mi geliştirdiniz. Şu an sadece bir şey görünce mesaj alacak kodunuz. Bu değişiklik kodlarınızı etkilemiş olabilir. Önce sorunun bundan kaynaklanıp kaynaklanmadığını anlayalım. Kodlarınızı bu yeni duruma göre adapte etmek zor olur mu? Eğer zor olur derseniz eskisi gibi hiç bir şey görmese de mesaj gönderen versiyona geçireceğim.

**Comment by kadirozgun** [comment]
Merhabalar Okan Bey, 
Slack üzerinden ekran görüntüsüyle beraber de bildirdim az önce. Terörist üzerinden geçen ve skidpad kamerasında da görülen terörist sensör tarafından yakalanmamakta maalesef. Ve anladığım kadarıyla kamera açısı da sürekli zephyre göre (oryantasyonuna göre) değişmekte ve bu da ilk konuştuğumuz youtube canlı yayınına göre olmaması gereken bir şey sanırım. Çünkü orada zephyr ya da iris bir ev ya da insan üzerinden geçtiğinde sensörün bunu göreceğini konuşmuştuk o nedenle kamera üzerinde oynama yapılmayacağını söylemiştiniz. Bu durumlar ile ilgili bilgilendirirseniz sevinirim. Kameranın gördüğü terörist ve veri okumama ekran görüntüsünü slack üzerinden paylaştım.
Saygılarımla.
