### ISSUE TITLE
simülasyon çalıştırmada hata

### ISSUE THREAD

**Issue by elifakdag** [teknofest-suruiha/suruiha#2]
Merhaba, simülasyonu çalıştırmak için wiki'de paylaştığınız komutu çalıştırıyorum fakat aşağıdaki hatayı alıyorum, aynı şekilde iris için de denedim onda da aynı hata return etti. 
Not: Araçları vs. kurma aşamasında herhangi bir hata ile karşılaşmadım.

```
elif@elif:~/catkin_ws/src/suruiha$ roslaunch uav_gazebo zephyr_runway.launch
WARNING: unable to configure logging. No log files will be generated
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Invalid <param> tag: Cannot load command parameter [rosversion]: command [rosversion roslaunch] returned with code [1]. 

Param xml is <param command="rosversion roslaunch" name="rosversion"/>
The traceback for the exception was written to the log file
No handlers could be found for logger "roslaunch"

```

**Comment by okanasik** [comment]
Merhabalar, 

Sorun `/home/elif/.bashrc` dosyasına eklenen betiklerde gibi görünüyor. `.bashrc` dosyası ile ilgili adımları kontrol edebilir misiniz? Bir de `.bashrc` dosyasında değişiklik yaptıktan sonra diğer adımları yeni terminal ekranında yapmanız gerekiyordur. İsterseniz `.bashrc` dosyasının içeriğini buraya paylaşın bir sorun var mı bakalım.

**Comment by elifakdag** [comment]
`.bashrc`'ye sizin söylediğiniz gibi şu komutları ekledim. Tüm terminalleri kapattım fakat yine olmadı.


`.bashrc`'de bulunan içerik;
```
#suru iha icin simulasyon programı
source /opt/ros/kinetic/setup.bash
source /home/elif/catkin_ws/devel/setup.bash
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH/home/elif/catkin_ws/src
export GAZEBO_MODEL_PATH=/home/elif/catkin_ws/src/suruiha/uav_description/gazebo_models/
export GAZEBO_PLUGIN_PATH=/home/elif/catkin_ws/devel/lib/
```

**Comment by gokceuludogan** [comment]
Merhaba,
Dokümantasyonda ufak bir hata olmuş. 
`export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH/home/elif/catkin_ws/src` satırını 
`export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:/home/elif/catkin_ws/src` ile değiştirip kurulumu tekrar yapabilir misiniz?

**Comment by okanasik** [comment]
Merhabalar,
Son düzeltmeden sonra kurulumla ilgili hatalarınızın çözüldüğünü varsayıyorum. Eğer hala hatalar ile karşılaşıyorsanız, lütfen yeni bir hata veya destek kaydı oluşturun.
