### ISSUE TITLE
Yeni Güncellemeler Hakkında

### ISSUE THREAD

**Issue by ghost** [teknofest-suruiha/suruiha#20]
@okanasik hocam merhaba.
Son gönderdiğiniz kodları çalıştırırken aşağıdaki hataları alıyorum.
```
gzclient: /usr/include/OGRE/OgreAxisAlignedBox.h:252: void Ogre::AxisAlignedBox::setExtents(const Ogre::Vector3&, const Ogre::Vector3&): Assertion `(min.x <= max.x && min.y <= max.y && min.z <= max.z) && "The minimum corner of the box must be less than or equal to maximum corner"' failed.
Aborted (core dumped)
[gazebo_gui-3] process has died [pid 16251, exit code 134, cmd /opt/ros/kinetic/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/home/m/.ros/log/d9630bb8-b5b4-11e8-8b19-8cdcd48515c8/gazebo_gui-3.log].
log file: /home/m/.ros/log/d9630bb8-b5b4-11e8-8b19-8cdcd48515c8/gazebo_gui-3*.log
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/zephyr/sensor, deleting message. This warning is printed only once.
```
Simülasyonu çalıştırdığım anda birden fazla topicten (20-30 kadarı) Queue limit reached for topic hatası alıyorum hemen.
Topicler asenkron olarak sürekli mesaj göndermekte sanırım.

**Comment by ghost** [comment]
Bu hataları her senaryo çalıştırmada görmüyorum fakat her iki üç çalıştırmada bir karşıma çıkmakta.

**Comment by okanasik** [comment]
Simulasyonu dudurulmuş şekilde başlatınca sorun çözülüyor. Bu yapabilmek için şu [https://github.com/teknofest-suruiha/suruiha/blob/master/scenarios/launch/run_scenario.launch](https://github.com/teknofest-suruiha/suruiha/blob/master/scenarios/launch/run_scenario.launch) dosyadaki 7. satırını `true` yapınca sorun çözülüyor. Simulasyon ekranı geldikten sonra sol alttaki düğmelerden play düğmesine basıp simülasyonu başlatıyoruz. Sonra takım kodlarını çalıştırabiliriz.

Asıl sebep bir şekilde render ortamı çalışmaya başlamadan simülator kamera sensörlerinin yerini değiştirmeye çalışınca Ogre'nin render makinası hataya sebep oluyor ve simülasyon kapanıyor.

**Comment by ghost** [comment]
@okanasik teşekkürler problemim çözüldü.
Yine de uyarı olarak aşağıdaki çıktıyı almaktayım. 
`[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/zephyr/pose/local/info, deleting message. This warning is printed only once.`
Bilginize...
Kolaylıklar...
