### ISSUE TITLE
Yeşil Alan Sınırları

### ISSUE THREAD

**Issue by ghost** [teknofest-suruiha/suruiha#21]
Merhaba.
Yaptığım testlerde bir İHA'nın yeşil alandan dışarı çıktığında simülasyonun durduğunu görmekteyim.
Özellikle sabit kanatlı İHA'larda dönüş ve iniş kalkış hareketlerinde pistin ıskalanması ile bu alanın dışına çıkılması çok olası bir durum.
Bir İHA'nın bu alanın dışına çıkması tüm simülasyonu durdurduğundan yarışma puanını olumsuz etkileyecek.
Bu konudaki önlemleri biz mi almalıyız yoksa siz ilgili arama alanınından daha büyük birer simülasyon ortamları mı hazırlayacaksınız yarışmada?
Örneğin bizim arama yapacağımız ve tüm olayların (arama, tespit, takip) gerçekleşeği alan 1000x1000 fakat simülasyon ortamı hata paylı olarak 1100x1100 vb.
Kolay gelsin.

**Comment by okanasik** [comment]
Bu önemli hatayı fark ettiğiniz için çok sağolun. biraz önce yaptığım değişiklikle https://github.com/teknofest-suruiha/suruiha/commit/cc6c7284b6396674723af39731d7b2240b60d921 çözülmüş olması gerekiyor. Kolaylıklar.
