### ISSUE TITLE
Simülasyon Süresi Hakkında

### ISSUE THREAD

**Issue by ghost** [teknofest-suruiha/suruiha#22]
@okanasik hocam selam.
Kodumda simülasyonun ne kadar süreceğini alabileceğim bir yöntem var mı?
Örnek senaryo toplamda 5 dakika sürmekte.
Bunu bir yerden çekebiliyor muyum?
Geliştirme dili olarak Python kullanıyorum.
Selamlar...

**Comment by okanasik** [comment]
Merhabalar,
Ne yazık ki simülasyonun ne kadar süreceğini bilmiyor olacaksınız. Bu bilgiye ulaşmanız mümkün değil.
