### ISSUE TITLE
Sensör Okuma İrtifa Aralıkları ve YAML Dosyası Hakkında

### ISSUE THREAD

**Issue by ghost** [teknofest-suruiha/suruiha#23]
Merhabalar.
Sensör okuma irtifa aralıkları ve YAML dosyası arasında sanırım bir bağımsızlık var.
İrtifaları YAML dosyasından değiştirdim fakat bu değişiklikleri sensörlerde göremedim.

**Comment by ghost** [comment]
Yaptığım testte zephyr0'nun aralıklarını 5 ve 200 olarak girip zephyr0 iha'yı çalıştırdım fakat rviz'deki patika gösterimi eskisi gibi 30'den sonra başladı. İrtifa 100 metrenin üzerine çıktıktan sonra da patikalar kayboldu.

**Comment by okanasik** [comment]
Merhabalar,
Evet, irtifaları değiştirebilmek için şu an hem model dosyasını hem de YAML dosyasını değiştirmek gerekiyor. Bu bilgiyi sadece YAML dosyasından alacak şekilde güncelleyeceğiz simülatörü.

**Comment by okanasik** [comment]
Merhabalar, şu https://github.com/teknofest-suruiha/suruiha/commit/09eded482bc3237807086b7e3180493ce80fca96 değişiklikle sensor algılama yüksekliği ve pil kapasitesi YAML dosyasından alınıyor artık.
