### ISSUE TITLE
İniş Kalkış İşlemleri Hakkında

### ISSUE THREAD

**Issue by ghost** [teknofest-suruiha/suruiha#25]
Merhaba @okanasik hocam.
Kalkış yaptıktan belirli bir süre sonra iniş yapıyorum.
İniş işlemleri bittikten sonra tekrar kalkış isteği yapıyorum.
`Air Traffic: READY_TO_TAKEOFF` oluyor fakat trafik yöneticisi İHA'yı kalkış noktasına yerleştirmiyor ve kalkmasına izin vermiyor.

**Comment by ghost** [comment]
İHA olarak zephyr kullanıyorum.
İniş yapıldıktan sonra yönetici, İHA'yı kalkış yapmadan önceki yerine yerleştiriyor fakat sonrasında kalkış isteği yaptığımda oradan alıp kalkış noktasına getirmiyor ve İHA kontrol sinyallerini almıyor.

**Comment by ghost** [comment]
Ayrıca yönetici, İHA'ların pilini yenileyip eski konumlarına koymuyor.
Battery replaced debug mesajı çıkıyor ama pille bu mesaj çıktığında yenilenmiyor.
Sanırım tekrar kalkış isteği yaptığımız anda piller yenileniyor.

**Comment by ghost** [comment]
Pillerin tekrar doldurulmasını kontrol edip bekleyerek bu problemi çözdüm fakat ilginiz için sorunu açık bırakıyorum.

**Comment by okanasik** [comment]
Merhabalar,
Eğer piller yenilendi mesajı yazıyorsa İHA'yı da başlangıç pozisyonuna yerleştirmiş olması gerekiyor. Ve pillerin de yenilenmesi gerekiyor. İnişten sonra kalkış için örnek kodları kullanıyorsanız. O kodların yapısındaki bir hatadan dolayı yeniden kalkış yapamıyordu. Örnek takım kodlarından `air_traffic_manager` modülündeki hatadan kaynaklanıyor. Burada bir sorun olmadığından emin olabilir misin? Bir de eğer İHA durmuyorsa İHA'yı inişe daha yavaş getirmeyi deneyebilirsin.

**Comment by ghost** [comment]
https://youtu.be/eateST_a9bs
