### ISSUE TITLE
models hatası

### ISSUE THREAD

**Issue by canibal1** [teknofest-suruiha/suruiha#5]
Gerekli kurulum işlemlerini yaptıktan sonra uçak kodlarını giriyorum gazebo açılıyor ama ucak modelleri görünmüyor. Models menüsünde isimleri var ama kendileri yok ne yapmalıyım?

**Comment by okanasik** [comment]
hangi uçak komutlarını (kodları değil de komut demek istediniz değil mi?) giriyorsunuz. Buraya yazabilir misiniz?

**Comment by canibal1** [comment]
Doğru pardon yanlış yazmışım. Şu komutu çalıştırdığımda uçak modelinin gazebonun içine gelmesi gerekiyor sanırsam ama gelmiyor. roslaunch uav_gazebo zephyr_runway.launch . Sadece orada bulunan zemin var . Models'te uçağın isimleri var zephyr0 zephyr1 zephyr2 ... diye ama kendileri yok

**Comment by okanasik** [comment]
Hımm. ilginç bir durum. Eğer models altında listeleniyorsa grafik ekranda da görünmesi gerekiyor. Peki bu komutu çalıştırınca konsol ekranında herhangi bir hata mesajı veya uyarı görünüyor mu? Bir de home dizini altındaki .bashrc betik dosyasını kontrol edip şu patikaların doğru ayarlandığından emin olabilir misiniz? `GAZEBO_MODEL_PATH` ve `GAZEBO_PLUGIN_PATH`

**Comment by canibal1** [comment]
Path'ları düzelttiğimde kaydetmeyi unutmuşum sorunu çözdüm teşekkür ederim.
