### ISSUE TITLE
catkin_make hatası

### ISSUE THREAD

**Issue by u-erdemir** [teknofest-suruiha/suruiha#6]
Merhabalar. 
Wikideki yönergeleri uygularken catkin_make ile indirilenleri derleniyordu. catkin_make aşağıdaki hatayı verdi. Hatanın kaynağı nedir ?
İyi akşamlar.

asus@asus-X555UB:~$ cd catkin_ws/
asus@asus-X555UB:~/catkin_ws$ catkin_make
Base path: /home/asus/catkin_ws
Source space: /home/asus/catkin_ws/src
Build space: /home/asus/catkin_ws/build
Devel space: /home/asus/catkin_ws/devel
Install space: /home/asus/catkin_ws/install
####
####
####
####
[  0%] Built target std_msgs_generate_messages_py
[  2%] Building CXX object suruiha/suruiha_gazebo_plugins/CMakeFiles/zephyr_controller.dir/src/controllers/zephyr_controller.cpp.o
[  5%] Building CXX object suruiha/suruiha_gazebo_plugins/CMakeFiles/air_traffic_controller.dir/src/air_traffic_controller/air_traffic_controller.cpp.o
[  5%] Built target _suruiha_gazebo_plugins_generate_messages_check_deps_AirTraffic
[  5%] Built target _suruiha_gazebo_plugins_generate_messages_check_deps_UAVMessage
[  8%] Building CXX object suruiha/suruiha_gazebo_plugins/CMakeFiles/zephyr_controller.dir/src/util/util.cpp.o
[ 11%] Building CXX object suruiha/suruiha_gazebo_plugins/CMakeFiles/zephyr_controller.dir/src/uav_sensor/uav_sensor.cpp.o
/home/asus/catkin_ws/src/suruiha/suruiha_gazebo_plugins/src/controllers/zephyr_controller.cpp:15:53: fatal error: suruiha_gazebo_plugins/UAVSensorMessage.h: No such file or directory
compilation terminated.
suruiha/suruiha_gazebo_plugins/CMakeFiles/zephyr_controller.dir/build.make:62: recipe for target 'suruiha/suruiha_gazebo_plugins/CMakeFiles/zephyr_controller.dir/src/controllers/zephyr_controller.cpp.o' failed
make[2]: *** [suruiha/suruiha_gazebo_plugins/CMakeFiles/zephyr_controller.dir/src/controllers/zephyr_controller.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 11%] Built target geometry_msgs_generate_messages_py
[ 11%] Built target _suruiha_gazebo_plugins_generate_messages_check_deps_UAVSensorMessage
[ 11%] Built target std_msgs_generate_messages_cpp
[ 11%] Built target geometry_msgs_generate_messages_cpp
[ 11%] Built target std_msgs_generate_messages_lisp
[ 11%] Built target geometry_msgs_generate_messages_lisp
[ 11%] Built target geometry_msgs_generate_messages_eus
[ 11%] Built target std_msgs_generate_messages_eus
[ 11%] Built target geometry_msgs_generate_messages_nodejs
[ 11%] Built target std_msgs_generate_messages_nodejs
[ 14%] Building CXX object suruiha/suruiha_gazebo_plugins/CMakeFiles/comm_manager.dir/src/comm_manager/comm_manager.cpp.o
/home/asus/catkin_ws/src/suruiha/suruiha_gazebo_plugins/src/uav_sensor/uav_sensor.cpp:8:53: fatal error: suruiha_gazebo_plugins/UAVSensorMessage.h: No such file or directory
compilation terminated.
suruiha/suruiha_gazebo_plugins/CMakeFiles/zephyr_controller.dir/build.make:134: recipe for target 'suruiha/suruiha_gazebo_plugins/CMakeFiles/zephyr_controller.dir/src/uav_sensor/uav_sensor.cpp.o' failed
make[2]: *** [suruiha/suruiha_gazebo_plugins/CMakeFiles/zephyr_controller.dir/src/uav_sensor/uav_sensor.cpp.o] Error 1
In file included from /home/asus/catkin_ws/src/suruiha/suruiha_gazebo_plugins/src/air_traffic_controller/air_traffic_controller.cpp:5:0:
/home/asus/catkin_ws/src/suruiha/suruiha_gazebo_plugins/include/suruiha_gazebo_plugins/air_traffic_controller/air_traffic_controller.h:11:47: fatal error: suruiha_gazebo_plugins/AirTraffic.h: No such file or directory
compilation terminated.
suruiha/suruiha_gazebo_plugins/CMakeFiles/air_traffic_controller.dir/build.make:62: recipe for target 'suruiha/suruiha_gazebo_plugins/CMakeFiles/air_traffic_controller.dir/src/air_traffic_controller/air_traffic_controller.cpp.o' failed
make[2]: *** [suruiha/suruiha_gazebo_plugins/CMakeFiles/air_traffic_controller.dir/src/air_traffic_controller/air_traffic_controller.cpp.o] Error 1
CMakeFiles/Makefile2:500: recipe for target 'suruiha/suruiha_gazebo_plugins/CMakeFiles/air_traffic_controller.dir/all' failed
make[1]: *** [suruiha/suruiha_gazebo_plugins/CMakeFiles/air_traffic_controller.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 25%] Built target iris_controller
In file included from /home/asus/catkin_ws/src/suruiha/suruiha_gazebo_plugins/src/comm_manager/comm_manager.cpp:4:0:
/home/asus/catkin_ws/src/suruiha/suruiha_gazebo_plugins/include/suruiha_gazebo_plugins/comm_manager/comm_manager.h:12:47: fatal error: suruiha_gazebo_plugins/UAVMessage.h: No such file or directory
compilation terminated.
suruiha/suruiha_gazebo_plugins/CMakeFiles/comm_manager.dir/build.make:62: recipe for target 'suruiha/suruiha_gazebo_plugins/CMakeFiles/comm_manager.dir/src/comm_manager/comm_manager.cpp.o' failed
make[2]: *** [suruiha/suruiha_gazebo_plugins/CMakeFiles/comm_manager.dir/src/comm_manager/comm_manager.cpp.o] Error 1
CMakeFiles/Makefile2:1135: recipe for target 'suruiha/suruiha_gazebo_plugins/CMakeFiles/comm_manager.dir/all' failed
make[1]: *** [suruiha/suruiha_gazebo_plugins/CMakeFiles/comm_manager.dir/all] Error 2
CMakeFiles/Makefile2:537: recipe for target 'suruiha/suruiha_gazebo_plugins/CMakeFiles/zephyr_controller.dir/all' failed
make[1]: *** [suruiha/suruiha_gazebo_plugins/CMakeFiles/zephyr_controller.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

**Comment by okanasik** [comment]
Tekrar `catkin_make` ile derleniz mi? ilk adımda kullanılan message header dosyasını bulamıyor çünkü henüz oluşturulmamış oluyor. ilk derlemeden sonra erişelebilir olup derlenmesi lazım.

**Comment by u-erdemir** [comment]
Sadece github dan dosyaları çekip src klasörüne attım. Sonrasında catkin_make yaptım. Bunun dışında yapılması gereken bir işlem mi var ?
Not: Önceki paylaşılan kodlar, catkin_ws klasöründe yoktur. Boş çalışma dosyası üzerine yaptım.

**Comment by okanasik** [comment]
Merhabalar,
Projenin CMake dosyasında ufak bir hatadan kaynaklı olarak asıl kodu derlemeden önce oluşturması gereken servis ve mesaj dosyalarını oluşturuyormuş. Son değişiklikle bu hata giderilmiş olması gerekiyor. Projenin son halini çekip deneyebilir misiniz?

**Comment by u-erdemir** [comment]
Son haliyle sorunsuz derleniyor. Teşekkürler.
