### ISSUE TITLE
roslaunch ve rosrun hatası

### ISSUE THREAD

**Issue by kadirozgun** [teknofest-suruiha/suruiha#7]
güncellenen sistemde "roslaunch uav_gazebo zephyr_runway.launch" kodunu yazdığımda hata veriyor.

[Err] [Plugin.hh:180] Failed to load plugin libair_traffic_controller.so: libair_traffic_controller.so: cannot open shared object file: No such file or directory
[Err] [Plugin.hh:180] Failed to load plugin libcomm_manager.so: libcomm_manager.so: cannot open shared object file: No such file or directory

 güncellenen sistemde "rosrun uav_sample_controller keyboard_controller.py _pose:=zephyr0_pose _control:=zephyr0_control _name:=zephyr0" kodunu girince import error veriyor.

Traceback (most recent call last):
  File "/home/teknofest/catkin_ws/src/uav_sample_controller/scripts/keyboard_controller.py", line 6, in <module>
    from suruiha_gazebo_plugins.srv import AirTraffic
ImportError: No module named suruiha_gazebo_plugins.srv

**Comment by okanasik** [comment]
depoyu güncelledikten sonra `catkin_ws` klasöründe `catkin_make` çalıştırıp yeni paketleri derlediniz mi?

**Comment by kadirozgun** [comment]
####
#### Running command: "make -j2 -l2" in "/home/teknofest/catkin_ws/build"
####
Scanning dependencies of target air_traffic_controller
Scanning dependencies of target zephyr_controller
[  2%] Building CXX object suruiha/suruiha_gazebo_plugins/CMakeFiles/air_traffic_controller.dir/src/air_traffic_controller/air_traffic_controller.cpp.o
[  5%] Building CXX object suruiha/suruiha_gazebo_plugins/CMakeFiles/zephyr_controller.dir/src/controllers/zephyr_controller.cpp.o
In file included from /home/teknofest/catkin_ws/src/suruiha/suruiha_gazebo_plugins/src/air_traffic_controller/air_traffic_controller.cpp:5:0:
/home/teknofest/catkin_ws/src/suruiha/suruiha_gazebo_plugins/include/suruiha_gazebo_plugins/air_traffic_controller/air_traffic_controller.h:11:47: fatal error: suruiha_gazebo_plugins/AirTraffic.h: No such file or directory
compilation terminated.
suruiha/suruiha_gazebo_plugins/CMakeFiles/air_traffic_controller.dir/build.make:62: recipe for target 'suruiha/suruiha_gazebo_plugins/CMakeFiles/air_traffic_controller.dir/src/air_traffic_controller/air_traffic_controller.cpp.o' failed
make[2]: *** [suruiha/suruiha_gazebo_plugins/CMakeFiles/air_traffic_controller.dir/src/air_traffic_controller/air_traffic_controller.cpp.o] Error 1
CMakeFiles/Makefile2:500: recipe for target 'suruiha/suruiha_gazebo_plugins/CMakeFiles/air_traffic_controller.dir/all' failed
make[1]: *** [suruiha/suruiha_gazebo_plugins/CMakeFiles/air_traffic_controller.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  8%] Building CXX object suruiha/suruiha_gazebo_plugins/CMakeFiles/zephyr_controller.dir/src/controllers/joint_control.cpp.o
/home/teknofest/catkin_ws/src/suruiha/suruiha_gazebo_plugins/src/controllers/zephyr_controller.cpp:15:53: fatal error: suruiha_gazebo_plugins/UAVSensorMessage.h: No such file or directory
compilation terminated.
suruiha/suruiha_gazebo_plugins/CMakeFiles/zephyr_controller.dir/build.make:62: recipe for target 'suruiha/suruiha_gazebo_plugins/CMakeFiles/zephyr_controller.dir/src/controllers/zephyr_controller.cpp.o' failed
make[2]: *** [suruiha/suruiha_gazebo_plugins/CMakeFiles/zephyr_controller.dir/src/controllers/zephyr_controller.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:537: recipe for target 'suruiha/suruiha_gazebo_plugins/CMakeFiles/zephyr_controller.dir/all' failed
make[1]: *** [suruiha/suruiha_gazebo_plugins/CMakeFiles/zephyr_controller.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j2 -l2" failed


bu şekilde bir hata alıyorum

**Comment by okanasik** [comment]
Merhabalar,

Projenin CMake dosyasında ufak bir hatadan kaynaklı olarak asıl kodu derlemeden önce oluşturması gereken servis ve mesaj dosyalarını oluşturuyormuş. Son değişiklikle bu hata giderilmiş olması gerekiyor. Projenin son halini çekip deneyebilir misiniz?
