### ISSUE TITLE
zephyr_runway.launch hatası

### ISSUE THREAD

**Issue by u-erdemir** [teknofest-suruiha/suruiha#8]
Merhabalar Okan bey.
Wiki üzerinden bahsettiğiniz yönergeleri izliyordum. roslaunch uav_gazebo zephyr_runway.launch şeklinde çalıştırdığımda gazebo, "preparing your world" kısmında takılı kalıyor ve aşağıdaki hatayı veriyor. 
Hata kanaatimce "uav_sensor" ile alakalı olabilir. Aynı şekilde iris_runway.launch dosyasını çalıştırdığımda hatasız gazeboda açılıyor ancak zephyr i barındıran dünyalarda sıkıntı çıkıyor.
İyi çalışmalar.

asus@asus-X555UB:~$ roslaunch uav_gazebo zephyr_runway.launch 
... logging to /home/asus/.ros/log/2dd653c0-8b9f-11e8-a5d4-80a5893dad71/roslaunch-asus-X555UB-2860.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://asus-X555UB:34075/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)

auto-starting new master
process[master]: started with pid [2871]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 2dd653c0-8b9f-11e8-a5d4-80a5893dad71
process[rosout-1]: started with pid [2884]
started core service [/rosout]
process[gazebo-2]: started with pid [2887]
process[gazebo_gui-3]: started with pid [2890]
Gazebo multi-robot simulator, version 9.2.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[ INFO] [1532037643.418768105]: Finished loading Gazebo ROS API Plugin.
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.0.105
[ INFO] [1532037643.420993887]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[Dbg] [air_traffic_controller.cpp:51] Checking model with name zephyr0
[Dbg] [air_traffic_controller.cpp:51] Checking model with name zephyr1
[Dbg] [air_traffic_controller.cpp:51] Checking model with name zephyr2
[Dbg] [air_traffic_controller.cpp:51] Checking model with name zephyr3
[Dbg] [air_traffic_controller.cpp:51] Checking model with name zephyr4
[Dbg] [air_traffic_controller.cpp:51] Checking model with name zephyr5
[Dbg] [air_traffic_controller.cpp:62] We have 6 many zephyr models
[Dbg] [air_traffic_controller.cpp:51] Checking model with name iris0
[Dbg] [air_traffic_controller.cpp:62] We have 0 many iris models
[Dbg] [comm_manager.cpp:51] Checking model with name zephyr0
[Dbg] [comm_manager.cpp:51] Checking model with name zephyr1
[Dbg] [comm_manager.cpp:51] Checking model with name zephyr2
[Dbg] [comm_manager.cpp:51] Checking model with name zephyr3
[Dbg] [comm_manager.cpp:51] Checking model with name zephyr4
[Dbg] [comm_manager.cpp:51] Checking model with name zephyr5
[Dbg] [comm_manager.cpp:59] We have 6 many zephyr models
[Dbg] [comm_manager.cpp:51] Checking model with name iris0
[Dbg] [comm_manager.cpp:59] We have 0 many iris models
[Dbg] [comm_manager.cpp:36] created broadcast topic name:comm_zephyr0
[Dbg] [comm_manager.cpp:36] created broadcast topic name:comm_zephyr1
[Dbg] [comm_manager.cpp:36] created broadcast topic name:comm_zephyr2
[Dbg] [comm_manager.cpp:36] created broadcast topic name:comm_zephyr3
[Dbg] [comm_manager.cpp:36] created broadcast topic name:comm_zephyr4
[Dbg] [comm_manager.cpp:36] created broadcast topic name:comm_zephyr5
[Dbg] [zephyr_controller.cpp:88] control_topic:zephyr0_control pose_topic:zephyr0_pose sensor_topic:zephyr0_sensor
Error [Element.cc:702] Missing element description for [uav_sensor]
Segmentation fault (core dumped)
[gazebo-2] process has died [pid 2887, exit code 139, cmd /opt/ros/kinetic/lib/gazebo_ros/gzserver -e ode --verbose /home/asus/catkin_ws/src/suruiha/uav_gazebo/worlds/zephyr_runway.world __name:=gazebo __log:=/home/asus/.ros/log/2dd653c0-8b9f-11e8-a5d4-80a5893dad71/gazebo-2.log].
log file: /home/asus/.ros/log/2dd653c0-8b9f-11e8-a5d4-80a5893dad71/gazebo-2*.log
^C[gazebo_gui-3] killing on exit
Segmentation fault (core dumped)
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
asus@asus-X555UB:~$

**Comment by okanasik** [comment]
Evet uav_sensor ile ilgili görünüyor ama mevcut kodun son halini alırsanız sorunsuz bir şekilde çalışması gerekiyor. Kodu geliştirirken aradaki bir değişiklikle oluşan hatalı kodu almışsınız sanırım.

**Comment by u-erdemir** [comment]
Kodun son halini denedim. Tekrar aynı hatayı verdi.

**Comment by okanasik** [comment]
Bu hata `uav_description` paketindeki `gazebo_models/zephyr_fixed_wing` dosyasından kaynaklanabilir. bu dosyanın içine bakıp son kısımda `uav_sensor` kısmının aşağıdaki gibi olduğundan emin olabilir misiniz?
```
      <uav_sensor>
        <update_rate>10</update_rate>
        <hfov>0.5</hfov>
        <aspect_ratio>1.3333</aspect_ratio>
        <max_height>100</max_height>
        <min_height>30</min_height>
        <far>10000</far>
        <near>0.1</near>
      </uav_sensor>
```
`zephyr_controller` kodu bu tagleri arayıp parametreleri okumaya çalışıyor.

**Comment by u-erdemir** [comment]
Sorunu çözdüm. İlk paylaştığnız kodu çalıştırmaya çalışırken modelleri .gazebo dosyasının içine atmıştım. Sistem, öncelikli olarak .gazebo/models içerisindeki eski zephyr modelini kullanıyormuş. O dosyayı silince catkin workspace içindeki modellerle açıldı.
İlginiz için teşekkürler Okan bey.
