### ISSUE TITLE
AN ERROR LAUNCH CODE

### ISSUE THREAD

**Issue by eneSadi** [teknofest-suruiha/suruiha#9]
until this code, ı progressed with no problem but this code causes an error like below

enesadi@eneSadi:~$ roslaunch uav_gazebo zephyr_runway.launch 

**[zephyr_runway.launch] is neither a launch file in package [uav_gazebo] nor is [uav_gazebo] a launch file name
The traceback for the exception was written to the log file**

AND ALSO

after that error, when ı opened a new terminal, ı came across this error (at first line)

**bash: /home/user/catkin_ws/devel/setup.bash: No such file or director**

**Comment by okanasik** [comment]
depodaki son değişiklikten sonra mı bu hataları aldınız?

**Comment by eneSadi** [comment]
dosyaları src'ye ekleyip catkin_make yaptıktan sonra .bashrc dosyasının da sonuna son 4 kodu ekledim. her şey normaldi. launch kodunu girince bu hatayı verdi

**Comment by okanasik** [comment]
daha önce çalıştırdınız mı? şu an ilk defa mı simülasyon ortamını deniyorsunuz? görünüşe göre ilk defa çalıştırdığınız `catkin_make` doğru şekilde çalışmamız. `catkin_make` çalıştıktan sonra `/home/user/catkin_ws/devel` ve `/home/user/catkin_ws/build` dizinleri oluşması gerekiyor. bu dizinlerin oluştuğudan emin olun lütfen.

**Comment by eneSadi** [comment]
ilk defa çalıştırıyorum similasyonu. İlk catkin_make ve 2. si 100de100 tamamlandı hatasız. o iki dizinin de oluşmasına özellikle dikkat ettim komuttan sonra oluşmuştu. takım arkadaşlarımla da uğraştık çözemedik.

**Comment by okanasik** [comment]
o halde `.bashrc` de yazan patikanın doğruluğunu kontrol edebilir misiniz? mesela bilgisayarınızın kullanıcısının adı `user` mi? yoksa buraya öylesine mi yazdınız.

**Comment by eneSadi** [comment]
kullanıcı adımı teknofest yazan kısımları eneSadi olarak değiştirdim yani kulllanıcı adım. 
bu hatayı (**bash: /home/user/catkin_ws/devel/setup.bash: No such file or director**) internette de arattım .bashrc dosyasında fazla kod olduğu yazıyordu, **gedit ~/.bashrc &** bu kodu kullanarak temizledim .bashrc dosyasındaki fazlalıkları (yani bulduğum kaynak öyle söylüyordu) ama hata giderilmedi launch kodu yine çalışmadı

**Comment by okanasik** [comment]
Merhaba,

`.bashrc` deki fazlalıkları nasıl tespit ettiniz. Sadece kurulum için gerekli yerleri eklemeniz yeterli olacaktır. Mevcut `.bashrc` dosyasının içeriğini paylaşabilir misiniz?

eğer kullanıcı adınız eneSadi ise `.bashrc` dosyasındaki patikalar şu şekilde değil mi?

```
source /home/eneSadi/catkin_ws/devel/setup.bash
```

eğer bu şekilde yazdıysanız `.bashrc` nasıl oluyor da `/home/user/catkin_ws/devel/setup.bash` bu patikadaki dosyayı arıyor pek anlamadım.

**Comment by eneSadi** [comment]
merhaba,
fazlalık temizleme işlemini yaptığımda kod olarak bir şey eksilmedi kontrol ettim. ayrıca her şeyi baştan 2 3 kere daha yaptım temizleme işlemi olmadan

source /home/eneSadi/catkin_ws/devel/setup.bash evet bu şekilde

/home/user/catkin_ws/devel/setup.bash bu dosyayı aramıyor ben genel bir örnek olması için user yapmıştım eneSadi'yi

.bashrc dosyası içeriğim şu şekilde: 


.
.
.
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

source /opt/ros/kinetic/setup.bash
source /home/eneSadi/catkin_ws/devel/setup.bash
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:/home/eneSadi/catkin_ws/src
export GAZEBO_MODEL_PATH=/home/eneSadi/catkin_ws/src/suruiha/uav_description/gazebo_models/
export GAZEBO_PLUGIN_PATH=/home/eneSadi/catkin_ws/devel/lib/

**Comment by okanasik** [comment]
`.bashrc` dosyasında bir sorun görünmüyor. `devel` dizininin varlığını kontrol edebilir misiniz?

**Comment by eneSadi** [comment]
devel dizini catkin_make aşamasında oluştu ve hala mevcut

bash: /home/eneSadi/catkin_ws/devel/setup.bash: No such file or director 
burada yok dediği setup.bash dosyası devel klasörünün içinde var

**Comment by okanasik** [comment]
kullanıcı adınız `eneSadi` mi yoksa `enesadi` mi? Siz dosya yöneticisinden `home` dizini altındaki kullanıcı dizinine bakabilir misiniz? Linux ortamında büyük-küçük harf farkı oluyor.

**Comment by eneSadi** [comment]
evet şuan farkettim küçük olmalıymış hemen deniyorum teşekkür ederim

**Comment by eneSadi** [comment]
denedim ve oldu similasyon ortamını açtım. Çok teşekkür ederim hocam iyi geceler...
